### ISSUE TITLE
option height: 'auto' displays horizontal scrolling bar in textarea

### ISSUE THREAD

**Issue by bricepepin** [nhnent/tui.editor#191]
## Version
1.1.1

## Test Environment
Windows 7 and Chrome 66

## Current Behavior
If you set the option `height: 'auto'` to the editor, you can see an horizontal scrolling bar in the middle of the textarea.

## Expected Behavior
Hide the scrolling bar. 

This can be done with something like this : 

```css
.CodeMirror-scroll {
    min-height: 145px;
}
````
